"use client";

import React, { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const FAQS = [
  {
    q: "How does the Anti-Fabrication Guardrail guarantee truthfulness?",
    a: "Our pipeline executes a strict verification check on every LLM output. It validates that every company name, job title, date range, and bullet count in the tailored output matches the candidate's original resume exactly. If the LLM tries to invent or exaggerate facts, the system rejects the output and triggers a single-retry prompt specifying the exact violations.",
  },
  {
    q: "Will my tailored resume pass ATS (Applicant Tracking Systems)?",
    a: "Yes. ATS scanners fail when resumes contain complex multi-column tables, floating text boxes, icons, or non-standard fonts. Our exported PDFs use a clean, single-column vector layout generated by @react-pdf/renderer using standard fonts and clear section titles.",
  },
  {
    q: "How is the Match Score calculated?",
    a: "The match score is a deterministic calculation: (Matched Skills / Total JD Required Skills) × 100%. Our skill matching engine normalizes plurals (APIs ↔ API), acronyms (SSR ↔ Server-Side Rendering), and suffix words (REST API integration ↔ REST APIs) so your score is transparent and accurate.",
  },
  {
    q: "What if a job description doesn't list explicit technical skill bullets?",
    a: "If a job posting is short or doesn't include bulleted requirements, our extraction pipeline automatically falls back to extracting key role responsibilities and domain keywords, diffing them against your experience bullets.",
  },
  {
    q: "Is my resume data stored or sold?",
    a: "No. Your resume data is processed in-memory during your session and sent to Gemini via secure encrypted API requests. We do not store or sell your resume content to third parties.",
  },
  {
    q: "Can I customize the generated bullets before downloading?",
    a: "Yes. You can review the reordered bullets and skill tags in the interactive results card before generating your final vector PDF.",
  },
];

export default function FAQPage() {
  const shouldReduceMotion = useReducedMotion();
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <div className="min-h-screen bg-[#0F1419] text-[#E5E7EB] flex flex-col font-sans relative overflow-x-hidden bg-grid-pattern">
      {/* Background glowing orb mesh */}
      <div className="absolute top-20 left-1/4 w-[500px] h-[500px] bg-glow-orb-1 pointer-events-none z-0" />
      <div className="absolute top-96 right-1/4 w-[600px] h-[600px] bg-glow-orb-2 pointer-events-none z-0" />

      <Navbar />

      <main className="relative z-10 flex-1 max-w-4xl mx-auto px-6 md:px-8 py-16 w-full">
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <span className="font-label text-xs uppercase tracking-widest text-[#3654FF] font-bold">
            KNOWLEDGE BASE
          </span>
          <h1 className="font-heading text-4xl sm:text-5xl font-extrabold tracking-tight text-white mt-2 mb-4">
            Frequently Asked <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#3654FF] via-[#5B73FF] to-[#1F9D6B]">Questions</span>
          </h1>
          <p className="text-[#9CA3AF] text-lg leading-relaxed">
            Everything you need to know about ATS optimization, fact verification, and how our skill diffing engine works.
          </p>
        </div>

        {/* FAQ Accordion with Glassmorphism Cards */}
        <div className="space-y-4 mb-16">
          {FAQS.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="rounded-2xl bg-[#161B22]/90 border border-[#2A303C] hover:border-[#3654FF]/40 backdrop-blur-xl shadow-xl overflow-hidden transition-all"
              >
                <button
                  onClick={() => toggle(idx)}
                  className="w-full p-6 text-left flex items-center justify-between gap-4 font-heading font-bold text-white hover:text-[#3654FF] transition-colors cursor-pointer text-base"
                >
                  <span>{faq.q}</span>
                  <span className="text-xl text-[#3654FF] font-bold">
                    {isOpen ? "−" : "+"}
                  </span>
                </button>

                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="px-6 pb-6 text-sm text-[#9CA3AF] leading-relaxed border-t border-[#2A303C]/50 pt-4 font-sans"
                    >
                      {faq.a}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

        {/* CTA Banner */}
        <div className="p-8 rounded-3xl bg-gradient-to-r from-[#161B22] via-[#1E2638] to-[#161B22] border border-[#3654FF]/40 text-center flex flex-col items-center shadow-2xl backdrop-blur-xl">
          <h2 className="font-heading text-2xl font-extrabold text-white mb-2 tracking-tight">
            Ready to build a tailored resume?
          </h2>
          <p className="text-[#9CA3AF] text-sm mb-6 leading-relaxed">
            Get an instant match score and ATS PDF in seconds.
          </p>
          <Link
            href="/app"
            className="bg-gradient-to-r from-[#3654FF] to-[#5B73FF] hover:from-[#2A44E0] hover:to-[#4A62FF] text-white px-8 py-3 rounded-xl font-heading font-semibold text-sm transition-all shadow-lg shadow-indigo-500/25"
          >
            Launch Workspace →
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
